[project]
icon = "https://ijskoud.dev/assets/svg/logo.svg"
version = "1.0.0"

[variables]
information = "Just a template, like an uncolored drawing. That's all. ✏️"
installation = "To use this template, you will need the following: `pnpm` and `node >= 18.16.x`."